# Generated by Django 2.1.15 on 2025-09-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
    ]
